### PR TITLE
Re-add rust-boml

### LINKED ISSUE #8: boml and taplo don't work
All the taplo decoder tests currently fail because `taplo-decoder` doesn't get built. I'm not sure why this happens 🤔

For boml, all the encoder tests fail because `boml-encoder` doesn't get built; the `./run setup rust-boml` command issues a bunch of compile errors.

Not sure if I'm doing something wrong? Taplo used to work, but I haven't run boml since it was added.

My environment:

    % rustc --version
    rustc 1.86.0 (05f9846f8 2025-03-31) (Void Linux)

    % cargo --version
    cargo 1.86.0

Maybe my Rust is too new?

Would you mind taking a look when you have time @epage? No hurries.

Errors:

```
% ./run setup rust-boml
== rust-boml: warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
 --> rust-toml_edit-perf/src/main.rs:7:40
  |
7 |     let value = raw.parse::<toml_edit::Document>();
  |                                        ^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: `rust-toml_edit-perf` (bin "rust-toml_edit-perf") generated 1 warning
   Compiling time v0.3.29
warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
  --> rust-toml_edit/src/decoder.rs:19:24
   |
19 |     value: &toml_edit::Document,
   |                        ^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
  --> rust-toml_edit/src/decoder.rs:12:33
   |
12 |             .parse::<toml_edit::Document>()
   |                                 ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
  --> rust-toml_edit/src/encoder.rs:17:24
   |
17 | ) -> Result<toml_edit::Document, toml_test_harness::Error> {
   |                        ^^^^^^^^

warning: use of deprecated type alias `toml_edit::Document`: Replaced with `DocumentMut`
  --> rust-toml_edit/src/encoder.rs:19:30
   |
19 |     let mut doc = toml_edit::Document::new();
   |                              ^^^^^^^^

   Compiling rust-boml v0.0.0 (/home/martin/code/Toml/toml-test-matrix/scripts/rust-boml)
warning: `rust-toml_edit` (lib) generated 4 warnings
error[E0532]: expected unit struct, unit variant or constant, found tuple variant `boml::types::TomlValue::OffsetDateTime`
  --> rust-boml/src/decoder.rs:31:9
   |
31 |         boml::types::TomlValue::OffsetDateTime => Ok(toml_test_harness::Decoded::Value(
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
  ::: /home/martin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/boml-1.0.1/src/types.rs:51:2
   |
51 |     OffsetDateTime(OffsetTomlDateTime),
   |     -------------- `boml::types::TomlValue::OffsetDateTime` defined here
   |
help: use the tuple variant pattern syntax instead
   |
31 |         boml::types::TomlValue::OffsetDateTime(_) => Ok(toml_test_harness::Decoded::Value(
   |                                               +++
help: consider importing this unit variant instead
   |
1  + use boml::prelude::TomlValueType::OffsetDateTime;
   |
help: if you import `OffsetDateTime`, refer to it directly
   |
31 -         boml::types::TomlValue::OffsetDateTime => Ok(toml_test_harness::Decoded::Value(
31 +         OffsetDateTime => Ok(toml_test_harness::Decoded::Value(
   |

error[E0412]: cannot find type `Table` in module `boml::table`
  --> rust-boml/src/decoder.rs:55:26
   |
55 |     value: &boml::table::Table,
   |                          ^^^^^ not found in `boml::table`
   |
help: there is an enum variant `boml::prelude::TomlValue::Table` and 4 others; try using the variant's enum
   |
55 -     value: &boml::table::Table,
55 +     value: &boml::prelude::TomlValue,
   |
55 -     value: &boml::table::Table,
55 +     value: &boml::prelude::TomlValueType,
   |
55 -     value: &boml::table::Table,
55 +     value: &toml_test::decoded::Decoded,
   |
55 -     value: &boml::table::Table,
55 +     value: &toml_test_harness::Decoded,
   |

error[E0599]: no method named `into_table` found for struct `Toml<'_>` in the current scope
  --> rust-boml/src/decoder.rs:13:14
   |
11 |           let table = boml::Toml::parse(&data)
   |  _____________________-
12 | |             .map_err(|err| toml_test_harness::Error::new(format!("{err:?}")))?
13 | |             .into_table();
   | |_____________-^^^^^^^^^^
   |
help: there is a method `get_table` with a similar name, but with different arguments
  --> /home/martin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/boml-1.0.1/src/table.rs:25:2
   |
25 |     pub fn get_table(&self, key: &str) -> Result<&Self, TomlGetError<'_, 'a>> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0599]: no variant or associated item named `LocalDateTime` found for enum `TomlValue` in the current scope
  --> rust-boml/src/decoder.rs:34:33
   |
34 |         boml::types::TomlValue::LocalDateTime => Ok(toml_test_harness::Decoded::Value(
   |                                 ^^^^^^^^^^^^^ variant or associated item not found in `TomlValue<'_>`

error[E0599]: no variant or associated item named `LocalDate` found for enum `TomlValue` in the current scope
  --> rust-boml/src/decoder.rs:37:33
   |
37 |         boml::types::TomlValue::LocalDate => Ok(toml_test_harness::Decoded::Value(
   |                                 ^^^^^^^^^ variant or associated item not found in `TomlValue<'_>`

error[E0599]: no variant or associated item named `LocalTime` found for enum `TomlValue` in the current scope
  --> rust-boml/src/decoder.rs:40:33
   |
40 |         boml::types::TomlValue::LocalTime => Ok(toml_test_harness::Decoded::Value(
   |                                 ^^^^^^^^^ variant or associated item not found in `TomlValue<'_>`

error[E0023]: this pattern has 1 field, but the corresponding tuple variant has 2 fields
  --> rust-boml/src/decoder.rs:46:39
   |
46 |         boml::types::TomlValue::Array(v) => {
   |                                       ^ expected 2 fields, found 1
   |
  ::: /home/martin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/boml-1.0.1/src/types.rs:54:8
   |
54 |     Array(Vec<Self>, bool),
   |           ---------  ---- tuple variant has 2 fields
   |
help: use `_` to explicitly ignore each field
   |
46 |         boml::types::TomlValue::Array(v, _) => {
   |                                        +++

Some errors have detailed explanations: E0023, E0412, E0532, E0599.
For more information about an error, try `rustc --explain E0023`.
error: could not compile `rust-boml` (lib) due to 7 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0282]: type annotations needed for `Box<_>`
  --> /home/martin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`

For more information about this error, try `rustc --explain E0282`.
error: could not compile `time` (lib) due to 1 previous error
```

### PR DESCRIPTION
**Pull request by epage**
Boml was broken in 84a93ff when `boml` was upgraded from 0.3 to 1.0.1 (a breaking upgrade) and then removed in 9d30cf2.

This restores boml support to the last known working state and then takes the steps needed to upgrade it.

Fixes #8

### CODE REVIEW

**Comment by arp242** [comment]
Cheers; it looks like `./scripts/target/release/boml-encoder` doesn't exist (yet? any more?)

Should also remove `skip 1` from parsers/rust-boml.zsh; that is:

```
diff --git i/parsers/rust-boml.zsh w/parsers/rust-boml.zsh
index f9b6b51..238a4c8 100644
--- i/parsers/rust-boml.zsh
+++ w/parsers/rust-boml.zsh
@@ -6,13 +6,12 @@ setup() {
 }

 typeset -A info=(
-       skip    1
        lang    'Rust'
        toml    '1.0'
        site    'https://github.com/Bright-Shard/boml'
        src     '' # We use the Cargo.toml for now 'https://github.com/toml-rs/toml.git'
        version '0.3.1'
        decoder './scripts/target/release/boml-decoder'
-       encoder './scripts/target/release/boml-encoder'
+       encoder 'TODO'
        perf    './scripts/target/release/rust-boml-perf'
 )
```

**Comment by epage** [comment]
> Cheers; it looks like ./scripts/target/release/boml-encoder doesn't exist (yet? any more?)

Never did.  I assume oversight from when BOML was added

> Should also remove skip 1 from parsers/rust-boml.zsh; that is:

Fixed.  Accidentally got mixed up on branches.

**Comment by arp242** [comment]
Looks like boml just doesn't support encoding at all? In that case it should be an empty string (`''`) rather than `TODO`. That will show up as `(doesn't include encoder)` in the HTML, rather than `(TODO)`.

**Comment by arp242** [comment]
I'll get that fixed in a minute by the way; don't need to change it. I also need to run the benchmark on my laptop and update the output (not ideal, but not sure how to get consistent-y numbers otherwise).

**Comment by arp242** [comment]
The performance script fails with:

```
% toml-test -cat $(( 1024 * 5 )) >x.toml

% ./scripts/target/release/rust-boml-perf x.toml

thread 'main' panicked at rust-boml-perf/src/main.rs:9:11:
called `Result::unwrap()` on an `Err` value: Error: NumberTooLarge at `50000000000000000000`
In:
  flt2 = 3.1415
  flt3 = -0.01
  flt4 = 50000000000000000000000.0
  flt5 = 1000000.0
  flt6 = -0.02
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
zsh: IOT instruction  ./scripts/target/release/rust-boml-perf x.toml
```

That's actually a bug in toml-test; it should write out `flt4 = 5e+22` as per the input file. Need to look at that later.
